# Generated by Django 5.0.1 on 2026-06-24 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('FIELD_AGENT', 'Agent de terrain'), ('SECRETARY', 'Secrétariat'), ('CLIENT', 'Client (Citoyen)')], default='CLIENT', max_length=20, verbose_name='Rôle')),
                ('mfa_enabled', models.BooleanField(default=True, verbose_name='MFA activé')),
                ('mfa_secret', models.CharField(blank=True, max_length=32, verbose_name='Clé secrète MFA')),
                ('mfa_verified', models.BooleanField(default=False, verbose_name='MFA vérifié')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='Matricule employé')),
                ('assignment_zone', models.CharField(blank=True, max_length=100, verbose_name="Zone d'affectation")),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'identité nationale")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
