# Generated by Django 5.0.1 on 2026-06-24 04:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='N° de facture')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence unique')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant TVA')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant total TTC')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant payé')),
                ('montant_restant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant restant')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(help_text='Date limite de paiement', verbose_name="Date d'échéance")),
                ('date_paiement_complet', models.DateField(blank=True, null=True, verbose_name='Date de paiement complet')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=30, verbose_name='Statut')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/pdf/%Y/%m/', verbose_name='Facture PDF')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email envoyé au client')),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'email")),
                ('description', models.TextField(help_text='Détails de la facture (type de concession, caveau, etc.)', verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.concession', verbose_name='Concession')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence unique')),
                ('numero_transaction', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='N° de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence Mobile Money, numéro de chèque, etc.', max_length=200, verbose_name='Référence transaction externe')),
                ('numero_telephone', models.CharField(blank=True, help_text='Pour Mobile Money / Airtel Money', max_length=20, verbose_name='Numéro de téléphone')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('REMBOURSE', 'Remboursé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='billing.facture', verbose_name='Facture')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TransactionFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence unique')),
                ('type_transaction', models.CharField(choices=[('PAIEMENT_RECUE', 'Paiement reçu'), ('FACTURE_EMISE', 'Facture émise'), ('REMBOURSEMENT', 'Remboursement'), ('AJUSTEMENT', 'Ajustement'), ('ANNULATION', 'Annulation')], max_length=30, verbose_name='Type de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('sens', models.CharField(choices=[('ENTREE', 'Entrée (recette)'), ('SORTIE', 'Sortie (dépense)')], default='ENTREE', max_length=10, verbose_name='Sens')),
                ('description', models.TextField(verbose_name='Description de la transaction')),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la transaction')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Client concerné')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.facture', verbose_name='Facture liée')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.paiement', verbose_name='Paiement lié')),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='billing_fac_statut_4b6d25_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client', 'statut'], name='billing_fac_client__0480dc_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_echeance'], name='billing_fac_date_ec_87f93b_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='billing_pai_statut_0f4507_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['client', 'statut'], name='billing_pai_client__ab8c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['mode_paiement'], name='billing_pai_mode_pa_25d384_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionfinanciere',
            index=models.Index(fields=['type_transaction'], name='billing_tra_type_tr_8f175d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionfinanciere',
            index=models.Index(fields=['sens'], name='billing_tra_sens_efa9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionfinanciere',
            index=models.Index(fields=['client', 'date_transaction'], name='billing_tra_client__e8776c_idx'),
        ),
    ]
