# Generated by Django 5.0.1 on 2026-06-24 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_codes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code MFA',
                'verbose_name_plural': 'Codes MFA',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'utilise'], name='mfa_mfacode_utilisa_bbc85d_idx'), models.Index(fields=['date_expiration'], name='mfa_mfacode_date_ex_207a59_idx')],
            },
        ),
    ]
