# Generated by Django 5.0.1 on 2026-06-24 04:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(blank=True, max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='M', max_length=1)),
                ('numero_identite', models.CharField(blank=True, max_length=50)),
                ('nom_pere', models.CharField(blank=True, max_length=100)),
                ('nom_mere', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='defunts/photos/', verbose_name='Photo')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('numero_acte_deces', models.CharField(blank=True, max_length=50, verbose_name='N° acte de décès')),
                ('notes', models.TextField(blank=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Défunt',
                'verbose_name_plural': 'Défunts',
                'ordering': ['-date_deces', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametreCimetiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cimetière')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('coordonnees_centre', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordonnées GPS du centre du cimetière', null=True, srid=4326, verbose_name='Coordonnées du centre')),
                ('superficie_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superficie totale (m²)')),
                ('longueur_standard_caveau', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Longueur standard caveau (m)')),
                ('largeur_standard_caveau', models.DecimalField(decimal_places=2, default=1.2, max_digits=5, verbose_name='Largeur standard caveau (m)')),
                ('largeur_allee', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Largeur allée (m)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Paramètre du cimetière',
                'verbose_name_plural': 'Paramètres du cimetière',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_zone', models.CharField(choices=[('SECTION', 'Section'), ('BLOC', 'Bloc'), ('ALLEE', 'Allée'), ('AUTRE', 'Autre')], default='SECTION', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('est_exploitable', models.BooleanField(default=True)),
                ('superficie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coordonnees_gps', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('OCCUPE', 'Occupé'), ('NON_EXPLOITABLE', 'Non exploitable')], default='DISPONIBLE', max_length=20)),
                ('type_caveau', models.CharField(choices=[('INDIVIDUEL', 'Individuel'), ('FAMILIAL', 'Familial'), ('COLLECTIF', 'Collectif'), ('URNAAIRE', 'Urinaire')], default='INDIVIDUEL', max_length=20)),
                ('longueur', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('largeur', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('profondeur', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('prix_concession', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_perpetuite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('position_gps', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Position GPS')),
                ('rangee', models.CharField(blank=True, max_length=20, verbose_name='Rangée')),
                ('numero_place', models.CharField(blank=True, max_length=20, verbose_name='Numéro de place')),
                ('coordonnees_gps', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caveaux_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caveaux', to='core.zone')),
            ],
            options={
                'verbose_name': 'Caveau',
                'verbose_name_plural': 'Caveaux',
                'ordering': ['zone', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=50, unique=True)),
                ('type_concession', models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('PERPETUELLE', 'Perpétuelle')], default='TEMPORAIRE', max_length=20)),
                ('duree_annees', models.IntegerField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_signature', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée'), ('RENOUVELEE', 'Renouvelée')], default='ACTIVE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('document_contrat', models.FileField(blank=True, upload_to='concessions/documents/', verbose_name='Document du contrat')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='core.caveau')),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('defunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions', to='core.defunt')),
            ],
            options={
                'verbose_name': 'Concession',
                'verbose_name_plural': 'Concessions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inhumation', models.DateField()),
                ('profondeur', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Profondeur (m)')),
                ('numero_place_dans_caveau', models.CharField(blank=True, max_length=20, verbose_name='N° place dans caveau')),
                ('notes', models.TextField(blank=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhumations', to='core.concession')),
                ('defunt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inhumations', to='core.defunt')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhumations_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Inhumation',
                'verbose_name_plural': 'Inhumations',
                'ordering': ['-date_inhumation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeExhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(max_length=200, verbose_name='Nom du demandeur')),
                ('lien_parente', models.CharField(max_length=100, verbose_name='Lien de parenté')),
                ('telephone_demandeur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('destination', models.CharField(choices=[('AUTRE_CIMETIERE', 'Autre cimetière'), ('DOMICILE', 'Domicile familial'), ('CRAMATORIUM', 'Cramatorium'), ('AUTRE', 'Autre')], default='AUTRE_CIMETIERE', max_length=30, verbose_name='Destination')),
                ('autorisation_mairie', models.FileField(blank=True, upload_to='exhumations/autorisations/', verbose_name='Autorisation de la mairie')),
                ('proces_verbal', models.FileField(blank=True, upload_to='exhumations/proces_verbaux/', verbose_name='Procès-verbal')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('REALISEE', 'Réalisée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_exhumation', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('inhumation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_exhumation', to='core.inhumation', verbose_name='Inhumation concernée')),
            ],
            options={
                'verbose_name': "Demande d'exhumation",
                'verbose_name_plural': "Demandes d'exhumation",
                'ordering': ['-date_demande'],
            },
        ),
    ]
