# Generated by Django 5.0.1 on 2026-06-30 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeexhumation',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees_admin', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Référence unique')),
                ('demandeur_nom', models.CharField(max_length=150, verbose_name='Nom du demandeur')),
                ('demandeur_prenom', models.CharField(max_length=150, verbose_name='Prénom du demandeur')),
                ('demandeur_email', models.EmailField(max_length=254, verbose_name='Email du demandeur')),
                ('demandeur_telephone', models.CharField(max_length=20, verbose_name='Téléphone du demandeur')),
                ('demandeur_adresse', models.TextField(blank=True, verbose_name='Adresse du demandeur')),
                ('demandeur_lien_parente', models.CharField(max_length=100, verbose_name='Lien de parenté avec le défunt')),
                ('motif', models.CharField(choices=[('TRANSFERT', 'Transfert vers autre cimetière'), ('RAISONS_FAMILIALES', 'Raisons familiales'), ('TRAVAUX_PUBLICS', 'Travaux publics'), ('RENOUVELLEMENT', 'Renouvellement de concession'), ('AUTRE', 'Autre motif')], default='AUTRE', max_length=30, verbose_name="Motif de l'exhumation")),
                ('motif_autre_precision', models.TextField(blank=True, verbose_name='Précisions si autre motif')),
                ('date_exhumation_souhaitee', models.DateField(verbose_name="Date d'exhumation souhaitée")),
                ('destination', models.CharField(blank=True, help_text=' Nouveau cimetière, crématorium, etc.', max_length=255, verbose_name='Destination après exhumation')),
                ('statut', models.CharField(choices=[('DEMANDEE', 'Demandée'), ('EN_COURS', 'En cours de traitement'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('REALISEE', 'Réalisée'), ('ANNULEE', 'Annulée')], db_index=True, default='DEMANDEE', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('autorisation_exhumation', models.FileField(blank=True, upload_to='exhumations/autorisations/%Y/%m/', verbose_name="Autorisation d'exhumation")),
                ('proces_verbal', models.FileField(blank=True, upload_to='exhumations/proces_verbaux/%Y/%m/', verbose_name='Procès-verbal')),
                ('documents_support', models.JSONField(blank=True, default=list, help_text='Liste des documents joints (PI, certificats, etc.)', verbose_name='Documents de support')),
                ('commentaires_admin', models.TextField(blank=True, verbose_name="Commentaires de l'administration")),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation effective')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='core.concession', verbose_name='Concession concernée')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_creees_admin', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Exhumation',
                'verbose_name_plural': 'Exhumations',
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['statut'], name='core_exhuma_statut_59a30d_idx'), models.Index(fields=['reference'], name='core_exhuma_referen_db8a23_idx'), models.Index(fields=['concession'], name='core_exhuma_concess_5d29f1_idx')],
            },
        ),
    ]
