# Generated by Django 5.0.1 on 2026-06-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_demandeexhumation_valide_par_exhumation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caveau',
            name='type_caveau',
            field=models.CharField(choices=[('INDIVIDUEL', 'Individuel'), ('FAMILIAL', 'Familial'), ('COLLECTIF', 'Collectif'), ('URNAIRE', 'Urinaire')], default='INDIVIDUEL', max_length=20),
        ),
        migrations.DeleteModel(
            name='Exhumation',
        ),
    ]
