# Generated by Django 5.0.1 on 2026-06-24 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defunt_nom', models.CharField(max_length=100, verbose_name='Nom du défunt')),
                ('defunt_prenom', models.CharField(max_length=100, verbose_name='Prénom du défunt')),
                ('date_deces', models.DateField(verbose_name='Date de décès')),
                ('lien_parente', models.CharField(max_length=50, verbose_name='Lien de parenté avec le demandeur')),
                ('telephone_contact', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation (Orange)'), ('VALIDEE', "Validée par l'admin (Rouge)"), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name='Motif de refus')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.caveau', verbose_name='Caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Demande de réservation',
                'verbose_name_plural': 'Demandes de réservation',
                'ordering': ['-date_demande'],
            },
        ),
    ]
