# Generated by Django 5.0.1 on 2026-06-24 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_rapport', models.CharField(choices=[('OCCUPATION', "Taux d'occupation"), ('FINANCIER', 'Rapport financier'), ('CONCESSIONS', 'Concessions'), ('DEFUNTS', 'Défunts'), ('EXPIRATIONS', 'Concessions expirantes'), ('PERSONNALISE', 'Rapport personnalisé')], default='OCCUPATION', max_length=20)),
                ('format_export', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('fichier', models.FileField(upload_to='rapports/%Y/%m/')),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('nombre_lignes', models.IntegerField(default=0)),
                ('taille_fichier', models.BigIntegerField(default=0)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport généré',
                'verbose_name_plural': 'Rapports générés',
                'ordering': ['-date_generation'],
            },
        ),
    ]
