# Generated by Django 5.0.1 on 2026-06-24 04:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence unique')),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('type_email', models.CharField(choices=[('MFA_CODE', 'Code MFA'), ('BIENVENUE', 'Email de bienvenue'), ('CONFIRMATION_RESERVATION', 'Confirmation de réservation'), ('FACTURE', 'Facture'), ('RAPPEL_PAIEMENT', 'Rappel de paiement'), ('ALERTE_CONCESSION', 'Alerte concession'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name="Type d'email")),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('contenu_html', models.TextField(verbose_name='Contenu HTML')),
                ('contenu_texte', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('pieces_jointes', models.JSONField(blank=True, default=list, help_text='Liste des chemins de fichiers joints', verbose_name='Pièces jointes')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('EN_ATTENTE', 'En attente')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('date_envoi_tente', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de tentative d'envoi")),
                ('date_envoi_reussi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi réussi")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recus', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
            ],
            options={
                'verbose_name': "Journal d'email",
                'verbose_name_plural': "Journaux d'emails",
                'ordering': ['-date_envoi_tente'],
                'indexes': [models.Index(fields=['statut'], name='notificatio_statut_1c28e5_idx'), models.Index(fields=['type_email'], name='notificatio_type_em_4d7a6f_idx'), models.Index(fields=['destinataire'], name='notificatio_destina_4abc88_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=20, verbose_name='Type')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='Priorité')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('url_lien', models.URLField(blank=True, verbose_name='Lien associé')),
                ('lue', models.BooleanField(db_index=True, default=False, verbose_name='Lue')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'lue'], name='notificatio_utilisa_74632e_idx'), models.Index(fields=['priorite'], name='notificatio_priorit_9af988_idx')],
            },
        ),
    ]
